# Generated by Django 5.0.3 on 2025-05-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_lesson'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lesson_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(to='diary.class'),
        ),
    ]
